@startuml Designing-a-system-p1-01

    !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

    LAYOUT_WITH_LEGEND()

     Enterprise_Boundary(b0, "District") {
        Person(customerSvc, "Customer Service", "")
        System(supplierBilling, "Supplier Billing System", "Reads customer usage<br/>information and creates bills and<br/>invoices for each household")
        System(districtSvr2, "Smart Meter Service", "")

        System(houses, "Houses", "In House Smart Meter", "Measures the amnount of energy<br/>that the house is using<br/>and sends that to the supplier")

        Rel(houses, districtSvr2, "send readings")
        Rel(customerSvc, districtSvr2, "")
        Rel(supplierBilling, districtSvr2, "read usage")
    }
@enduml

@startuml Designing-a-system-p1-02
    start

    repeat
    #PaleTurquoise:Read record
    from XML file;

    #PaleTurquoise:Process XML data;

    #PaleTurquoise:Save data to DB;
    repeat while (more records?) is (yes)

    stop
@enduml


@startuml Designing-a-system-p1-03
start

repeat
#PaleTurquoise:Read record
from XML file;

if (record read?) is (<color:green>succeeds) then 
    #PaleTurquoise:Process data record;
    if (record processing?) is (<color:green>succeeds) then 
        #PaleTurquoise:Save data to DB;
        if (save to DB?) is (<color:red>fails) then 
            #Red:Log error;
        endif
    else (<color:red>fails)
        #Red:Log error;
    endif
else (<color:red>fails)
    #Red:Log error;
endif
repeat while (more records?) is (yes)

stop
@enduml
